###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mysqlserver:
      image: mysql:5.7
      container_name: mysqlserver57
      #working_dir: /application
      volumes:
      #  - .:/application
      - ../db/data:/var/lib/mysql
      - ./config/mysql:/etc/mysql/conf.d
      environment:
        - MYSQL_ROOT_PASSWORD=rootpass
        - MYSQL_DATABASE=db1
        - MYSQL_USER=dbuser
        - MYSQL_PASSWORD=dbpass

    webserver:
      image: nginx:alpine
      container_name: webserver
      working_dir: /application
      volumes:
          - ../application:/application
          - ./config/nginx:/etc/nginx/conf.d/
      ports:
       - "80:80"
       - "3306:3306"

    phpfpm70:
      build: dockerenv/php-fpm
      container_name: phpfpm70
      working_dir: /application
      volumes:
        - ../application:/application
        - ./config/php-fpm/php-ini-overrides.ini:/etc/php/7.0/fpm/conf.d/99-overrides.ini
       #environment:
       #TZ: Asia/Taipei
