###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mysql:
      image: mysql:5.7
      container_name: jlinphp70-mysql
      working_dir: /application
      volumes:
        - ./config/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
        - ./dbdata:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=rootpass
        - MYSQL_DATABASE=db1
        - MYSQL_USER=dbuser
        - MYSQL_PASSWORD=dbpass

    webserver:
      image: nginx:alpine
      container_name: jlinphp70-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8500:80"

    php-fpm:
      build: dockerimg/php-fpm
      container_name: jlinphp70-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./config/php-fpm/php-ini-overrides.ini:/etc/php/7.0/fpm/conf.d/99-overrides.ini

